server:
  port: 8087
  servlet:
    context-path: /api

#environment dev/prod
spring:
  profiles:
    active: prod

  #Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: voting_microservice

#Openfeign
feign:
  client:
    config:
      efault: connectTimeout=5000
      readTimeout: 5000
