server:
  port: 8087
  servlet:
    context-path: /api

#environment dev/prod
spring:
  profiles:
    active: prod

#Openfeign
feign:
  client:
    config:
      efault: connectTimeout=5000
      readTimeout: 5000
